Repository NUWCDIVNPT/stig-manager, pull requests merged in 2023-08, with the labels that each got.

#1053 feat: STIG title column, hidden by default
  api/source/service/mysql/MetricsService.js
  api/source/specification/stig-manager.yaml
  client/src/js/SM/CollectionPanel.js
Labels: API, UI, OAS

#1052 feat: grid context-menu for clipboard copy
  client/src/css/stigman.css
  client/src/img/copy.svg
  client/src/js/SM/CollectionPanel.js
  client/src/js/SM/Global.js
  client/src/js/overrides.js
Labels: UI

#1054 pin sphinx container tag
  docs/build.sh
Labels: workflow
