Repository NUWCDIVNPT/stig-manager, pull requests merged in 2025-04, with the labels that each got.

#1583 feat: envvar for client OAuth2 response_mode
  api/source/bootstrap/client.js
  api/source/utils/config.js
  client/src/js/modules/oidcProvider.js
  docs/installation-and-setup/envvars.csv
Labels: API, UI, OIDC

#1578 deps: Update client modules to 1.5.1
  client/src/js/modules/package-lock.json
  client/src/js/modules/package.json
Labels: dependencies, UI

#1584 feat: user status ui
  client/src/css/stigman.css
  client/src/img/user-unavailable.svg
  client/src/js/SM/Grant.js
  client/src/js/SM/MainPanel.js
  client/src/js/SM/User.js
  client/src/js/SM/UserGroup.js
  docs/admin-guide/admin-guide.rst
  docs/assets/images/admin-user-grants.png
  docs/assets/images/admin-users.png
Labels: UI

#1608 fix: Fixes disappearing gear icon after modifying collection.
  client/src/js/SM/NavTree.js
Labels: UI

#1613 fix: use optional chaining in generateSharable
  client/src/js/SM/AppInfo.js
Labels: UI

#1610 refactor: createAssets dry run failure now returns 200.
  api/source/controllers/Asset.js
  api/source/specification/stig-manager.yaml
  client/src/js/SM/Manage.js
  test/api/mocha/data/asset/assetPost.test.js
Labels: API, OAS

#1605 refactor: Relocate import options to collection settings
  api/source/controllers/Collection.js
  api/source/service/CollectionService.js
  api/source/service/migrations/0039.js
  api/source/service/migrations/sql/current/10-stigman-tables.sql
  api/source/service/migrations/sql/current/20-stigman-static.sql
  api/source/specification/stig-manager.yaml
  client/src/js/SM/Cache.js
  client/src/js/SM/EventDispatcher.js
  client/src/js/SM/Manage.js
  client/src/js/SM/ReviewsImport.js
  test/api/appdata/appdata-meta-metrics-with-pin.jsonl
  test/api/appdata/appdata.jsonl
  test/api/appdata/batch-test-data.jsonl
  test/api/appdata/user-status-get-post.jsonl
  test/api/appdata/user-status-patch-put.jsonl
  test/api/mocha/cross-boundary/lvl1.test.js
  test/api/mocha/data/collection/collectionGet.test.js
  test/api/mocha/data/collection/collectionPatch.test.js
  test/api/mocha/data/collection/collectionPost.test.js
  test/api/mocha/data/collection/collectionPut.test.js
  test/api/mocha/data/collection/requestBodies.js
  test/api/mocha/data/review/reviewGet.test.js
  test/api/mocha/data/review/reviewPost.test.js
  test/api/mocha/integration/collection.test.js
  test/api/mocha/integration/deleteHandling.test.js
  test/api/mocha/integration/review.test.js
  test/api/mocha/referenceData.js
  test/api/mocha/utils/testUtils.js
Labels: API, OAS, DB, breaking
