Repository NUWCDIVNPT/stig-manager, pull requests merged in 2025-01, with the labels that each got.

#1464 fix: handle spaces in benchmarkId when used in class name
  client/src/js/collectionReview.js
  client/src/js/review.js
Labels: UI

#1472 db: change review_history.historyId to bigint
  api/source/service/migrations/0035.js
  test/api/form-data-files/appdata-meta-metrics-with-pin.jsonl
  test/api/form-data-files/appdata.jsonl
  test/api/form-data-files/batch-test-data.jsonl
Labels: tests, DB

#1474 feat: build x86 and arm64 alpine-based image
  .github/workflows/pub-docker.yml
Labels: Container, workflow

#1477 UI: fix for missing meta panel labels, double-click behavior
  client/src/js/SM/MetaPanel.js
Labels: UI

#1489 fix: api binary build
  api/launchers/stig-manager.bat
  api/launchers/stig-manager.sh
  api/pkg.config.json
Labels: Binaries
